upbit:
  accessKey: ${accessKey:NONE}
  markets: ${markets:NONE}
schedule:
  chunkSize: 100  
  collectDelay: 1000  # 시세수집 주기(ms)
  analysisScope: 60000  # 분석범위 (ms)

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect.storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: rivernine
