upbit:
  accessKey: ${accessKey:NONE}
  markets: ${markets:krw-btc}
schedule:
  chunkSize: 100  
  collectDelay: 1000  # 시세수집 주기(ms)
  analysisScope: 10  # 분석범위 (s)

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect.storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: rivernine
  batch.job.names: ${job.name:NONE}